<a href="https://colab.research.google.com/github/Bhavye2003Developer/Cheatsheets/blob/main/Word2Vec_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
!pip install gensim
import gensim
import gensim.downloader
from gensim.models import Word2Vec

In [67]:
available_models = list(gensim.downloader.info()['models'].keys())
len(available_models), available_models

(13,
 ['fasttext-wiki-news-subwords-300',
  'conceptnet-numberbatch-17-06-300',
  'word2vec-ruscorpora-300',
  'word2vec-google-news-300',
  'glove-wiki-gigaword-50',
  'glove-wiki-gigaword-100',
  'glove-wiki-gigaword-200',
  'glove-wiki-gigaword-300',
  'glove-twitter-25',
  'glove-twitter-50',
  'glove-twitter-100',
  'glove-twitter-200',
  '__testing_word2vec-matrix-synopsis'])

In [68]:
google_vector_model = gensim.downloader.load('word2vec-google-news-300')

In [69]:
google_vector_model.most_similar('Man')

[('Woman', 0.6939345002174377),
 ('Boy', 0.5896925330162048),
 ('Girl', 0.584598958492279),
 ('Suspect', 0.5577560067176819),
 ('Couple', 0.5528685450553894),
 ('man', 0.5316051840782166),
 ('Robber', 0.5315312743186951),
 ('Teenager', 0.5161930322647095),
 ('depicts_Michelangelo_Creation', 0.5148172378540039),
 ('Policeman', 0.5136396884918213)]

In [70]:
google_vector_model.similarity('i', 'I')

np.float32(0.5138725)

In [71]:
google_vector_model.cosine_similarities(google_vector_model['i'], [google_vector_model['I']])

array([0.51387244], dtype=float32)

In [72]:
google_vector_model['I'].shape

(300,)

In [73]:
google_vector_model.index_to_key[:10]

['</s>', 'in', 'for', 'that', 'is', 'on', '##', 'The', 'with', 'said']

In [74]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [75]:
nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [76]:
messages = pd.read_csv('./ham_spam_ds.csv')
print(messages.shape), messages.head()

(105, 2)


(None,
   label                                            message
 0   ham                        Hey where are you right now
 1  spam  Congratulations you have won a cash prize clic...
 2   ham                  Call me once you finish the class
 3   ham     I forgot my notebook can you bring it tomorrow
 4  spam     Limited time offer claim your free voucher now)

In [77]:
english_stopwords = stopwords.words('english')
english_stopwords.remove('not')
lemmatizer = WordNetLemmatizer()

def fetch_words(message):
    cleaned_message = re.sub(r'[^a-zA-Z0-9\s]', ' ', message)
    words = word_tokenize(cleaned_message.lower())
    lemmatized_tokens = [lemmatizer.lemmatize(token, pos='v') for token in words]
    return lemmatized_tokens

processed_words = messages['message'].apply(fetch_words).tolist()
processed_words

[['hey', 'where', 'be', 'you', 'right', 'now'],
 ['congratulations',
  'you',
  'have',
  'win',
  'a',
  'cash',
  'prize',
  'click',
  'link'],
 ['call', 'me', 'once', 'you', 'finish', 'the', 'class'],
 ['i', 'forget', 'my', 'notebook', 'can', 'you', 'bring', 'it', 'tomorrow'],
 ['limit', 'time', 'offer', 'claim', 'your', 'free', 'voucher', 'now'],
 ['be', 'we', 'meet', 'at', '5', 'or', 'later'],
 ['your', 'number', 'have', 'be', 'select', 'for', 'lucky', 'draw'],
 ['please', 'send', 'the', 'assignment', 'pdf'],
 ['get', 'instant', 'loan', 'approve', 'apply', 'now'],
 ['i', 'm', 'stick', 'in', 'traffic', 'might', 'be', 'late'],
 ['click', 'here', 'to', 'unlock', 'exclusive', 'reward'],
 ['free', 'recharge', 'wait', 'for', 'you', 'claim', 'today'],
 ['do', 'sir', 'say', 'anything', 'about', 'the', 'test'],
 ['let', 's', 'revise', 'chemistry', 'today'],
 ['win', 'excite', 'prize', 'participate', 'now'],
 ['good', 'night', 'see', 'you', 'tomorrow'],
 ['final', 'reminder', 'claim', 'you

In [78]:
model = Word2Vec(processed_words, epochs=100, vector_size=300)
model

In [79]:
model.wv.index_to_key

['you',
 'be',
 'the',
 'your',
 'now',
 'free',
 'today',
 'to',
 'for',
 'me',
 'click',
 'let',
 'do',
 'claim',
 'i',
 'this',
 's',
 'get',
 'please',
 'we',
 'can',
 'a',
 'have']

In [80]:
model.corpus_count

105

In [81]:
model.wv.similar_by_word('we')

[('you', 0.15833917260169983),
 ('this', 0.14361092448234558),
 ('today', 0.1377313882112503),
 ('free', 0.1291079819202423),
 ('have', 0.12523144483566284),
 ('for', 0.1107269749045372),
 ('now', 0.09627028554677963),
 ('s', 0.08651623874902725),
 ('click', 0.0792555958032608),
 ('claim', 0.07231957465410233)]

In [82]:
def avgWord2Vec(doc):

  vectors = []
  for word in doc:
    if word in model.wv.index_to_key:
      vectors.append(model.wv[word])
    else:
      vectors.append(np.zeros(300,))

  return np.mean(vectors, axis=0)

In [83]:
avgWord2Vec(processed_words[0])

array([-5.19221804e-04,  4.57389173e-04,  7.97256796e-04, -1.10924642e-04,
       -1.76317757e-04, -6.98103957e-04,  4.22601666e-04,  1.87735694e-03,
        4.56874783e-04, -1.16799132e-03,  9.56054777e-04, -4.02398931e-04,
       -5.20522997e-04,  2.13275528e-04, -7.57245774e-05, -9.38517662e-04,
        9.19654568e-04, -1.67792851e-04, -3.83840214e-04, -4.21656276e-04,
        3.25527712e-04,  1.18306591e-04,  1.02928433e-03,  1.28329311e-03,
       -3.75064747e-04,  2.53062569e-04, -3.65567510e-04,  1.28093861e-03,
       -5.22210845e-04,  4.66310788e-05, -5.42379314e-04, -3.75759007e-04,
        5.46092827e-04, -6.41827929e-04, -2.18735018e-04, -2.05034827e-04,
        6.80581511e-04, -1.27107619e-03, -5.21964190e-04,  2.19011864e-04,
       -7.28355197e-04,  9.92913013e-04, -1.50960269e-04, -5.14204012e-04,
       -1.13638668e-04, -3.78679190e-04,  1.49582619e-04,  1.48174401e-04,
       -3.79640240e-04,  8.61211670e-04,  6.84788489e-05, -1.24796594e-05,
       -1.07335371e-03, -

In [84]:
!pip install tqdm
from tqdm.auto import tqdm
tqdm.pandas(desc="Processing...")

In [85]:
processed_messages = []
for index in tqdm(range(len(processed_words))):
  processed_messages.append(avgWord2Vec(processed_words[index]))
processed_messages = np.array(processed_messages)

  0%|          | 0/105 [00:00<?, ?it/s]

In [86]:
X = pd.DataFrame(processed_messages)
X.head()

0         1         2         3         4         5         6    \
0 -0.000519  0.000457  0.000797 -0.000111 -0.000176 -0.000698  0.000423   
1 -0.000207  0.000791 -0.000308  0.000225 -0.000598 -0.000646  0.000076   
2  0.000525  0.000216  0.000091  0.000642 -0.000161 -0.000529  0.000898   
3  0.000308 -0.000336  0.000057  0.000286 -0.000291 -0.000791  0.000075   
4 -0.000623  0.000075 -0.000230 -0.000112 -0.000405 -0.000439 -0.000795   

        7         8         9    ...       290       291       292       293  \
0  0.001877  0.000457 -0.001168  ...  0.000824  0.001235  0.000708  0.000107   
1  0.000873 -0.000558 -0.000772  ...  0.000147  0.001020  0.001208 -0.000233   
2  0.000453 -0.000182 -0.000189  ... -0.000344  0.000937  0.000941  0.000228   
3  0.000699  0.000207  0.000335  ... -0.000244  0.000678  0.000864  0.000302   
4  0.000630 -0.000354 -0.000197  ...  0.001367  0.000330  0.000494  0.000251   

        294       295       296       297       298       299  
0  0.001458  0.000485  0.000448  0.000045  0.000429 -0.000525  
1  0.000962  0.000570  0.000661 -0.000089  0.000633 -0.000751  
2  0.001270  0.001082  0.000788  0.000043  0.000492 -0.000744  
3  0.001136  0.000522  0.000307  0.000309 -0.000058 -0.000353  
4  0.000476 -0.000030 -0.000333 -0.000248  0.000071 -0.000475  

[5 rows x 300 columns]

In [87]:
# processed_messages -> X
y = pd.get_dummies(messages['label'], dtype=int)[['spam']]
y[:10]

spam
0     0
1     1
2     0
3     0
4     1
5     0
6     1
7     0
8     1
9     0

In [88]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.20)
X_train.shape, X_test.shape, messages.shape

((84, 300), (21, 300), (105, 2))

In [89]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

spam_detect_model = RandomForestClassifier().fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


In [90]:
y_pred = spam_detect_model.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0])

In [91]:
print(accuracy_score(y_test, y_pred), '\n', classification_report(y_test, y_pred))

0.8095238095238095 
               precision    recall  f1-score   support

           0       0.75      0.75      0.75         8
           1       0.85      0.85      0.85        13

    accuracy                           0.81        21
   macro avg       0.80      0.80      0.80        21
weighted avg       0.81      0.81      0.81        21



In [92]:
def is_text_spam(text):

  words = fetch_words(text)
  vector = avgWord2Vec(words)
  is_spam = spam_detect_model.predict([vector])
  if (is_spam):
    return 'spam'
  return 'ham'

is_text_spam("how is it eveything?")

'ham'